import { useState } from 'react';
import type { BusinessProfile, ContentSet, ContentTone } from '../types';
import { PageHeader } from '../components/PageHeader';
import { CopyIcon, SparkIcon } from '../components/Icons';
import { aiProvider } from '../lib/ai';

const platforms: ContentSet['platform'][] = ['Instagram', 'Facebook', 'Google Business Profile'];
const tones: ContentTone[] = ['Promotional', 'Educational', 'Casual', 'Behind the scenes', 'Product highlight', 'Customer-focused'];

export function ContentPage({ profile, content, onContentGenerated, onToast, onEvent }: { profile: BusinessProfile; content: ContentSet | null; onContentGenerated: (content: ContentSet) => void; onToast: (message: string) => void; onEvent?: (name: string) => void }) {
  const [platform, setPlatform] = useState<ContentSet['platform']>(content?.platform ?? 'Instagram');
  const [tone, setTone] = useState<ContentTone>(content?.tone ?? 'Behind the scenes');
  const [busy, setBusy] = useState(false);
  const activeContent = content?.platform === platform && content.tone === tone ? content : null;
  const generate = async () => { setBusy(true); try { const text = await aiProvider.generateSocialPost(platform, tone, profile); onContentGenerated({ platform, tone, text, generatedAt: new Date().toISOString() }); } catch (error) { onToast(error instanceof Error ? error.message : 'Could not create a post.'); } finally { setBusy(false); } };
  const copy = async () => { if (activeContent) { await navigator.clipboard?.writeText(activeContent.text); onEvent?.('content_copied'); onToast('Post copied to clipboard.'); } };
  return <div className="page"><PageHeader eyebrow="CONTENT" title="What should you post today?" description="One useful, natural post is enough. Pick a place and a feeling—we’ll help with the words." action={<span className="not-automated"><span>●</span> You stay in control</span>} />
    <section className="content-layout"><div className="content-controls card"><div className="eyebrow">1. PICK A PLACE</div><div className="platform-list">{platforms.map((item) => <button key={item} className={platform === item ? 'selected' : ''} onClick={() => setPlatform(item)}><span className={`platform-mark ${item === 'Instagram' ? 'instagram' : item === 'Facebook' ? 'facebook' : 'google'}`}>{item === 'Instagram' ? '◎' : item === 'Facebook' ? 'f' : 'G'}</span>{item}<span className="radio-dot" /></button>)}</div><div className="eyebrow tone-label">2. PICK A FEELING</div><div className="tone-grid">{tones.map((item) => <button key={item} className={tone === item ? 'selected' : ''} onClick={() => setTone(item)}>{item}</button>)}</div><button className="button button-dark full-button" onClick={generate} disabled={busy}>{busy ? 'Finding the right words…' : activeContent ? 'Regenerate post' : 'Create my post'}<SparkIcon size={16} /></button></div><div className="content-output"><div className="post-preview-top"><span className="eyebrow">YOUR POST</span><span className="post-platform">{platform}</span></div>{activeContent ? <div className="generated-post"><div className="post-avatar">{profile.businessName.slice(0, 1)}</div><div className="post-body"><strong>{profile.businessName}</strong><span className="post-meta">Just now · {platform}</span><p>{activeContent.text}</p><div className="post-placeholder-image"><span>✦</span><small>A real photo from your business would work beautifully here.</small></div></div></div> : <div className="empty-content"><div className="content-sun">✦</div><h2>A good post starts<br />with something real.</h2><p>Choose a platform and a tone on the left. Your draft will show up here.</p></div>}<div className="output-bottom">{activeContent && <><button className="button button-dark" onClick={copy}><CopyIcon size={16} /> Copy post</button><span>Written for {tone.toLowerCase()} sharing</span></>}</div></div></section><div className="content-footnote"><SparkIcon size={15} /><span>Tip: add a real photo when you post. People connect with the place, not perfect copy.</span></div>
  </div>;
}
