import { useState } from 'react';
import type { BusinessProfile, Scores, ViewName } from '../types';
import { PageHeader } from '../components/PageHeader';
import { ScoreRing } from '../components/ScoreRing';
import { ArrowRightIcon, CheckIcon, ChevronDownIcon, ExternalIcon, InfoIcon, SparkIcon } from '../components/Icons';
import { nextActions, topIssues } from '../lib/scoring';

function ScoreRow({ label, value, color, detail }: { label: string; value: number | null; color: 'blue' | 'green' | 'amber'; detail: string }) {
  return <div className="score-row"><ScoreRing value={value} size="small" color={color} /><div className="score-row-main"><div><strong>{label}</strong><span>{value === null ? 'Not enough data' : detail}</span></div><div className="bar"><i className={color} style={{ width: `${value ?? 0}%` }} /></div></div></div>;
}

export function GrowthPage({ profile, scores, onNavigate, onCreateReport, onGeoCta, onVisibilityView }: { profile: BusinessProfile; scores: Scores; onNavigate: (view: ViewName) => void; onCreateReport: () => void; onGeoCta: () => void; onVisibilityView?: () => void }) {
  const [showAI, setShowAI] = useState(true);
  const issues = topIssues(profile, scores);
  const actions = nextActions(profile, scores);
  return <div className="page"><PageHeader eyebrow="GROWTH" title="See the bigger picture." description="A simple view of the things that help people discover, trust and choose your business." action={<button className="button button-light" onClick={onCreateReport}>Create free report <ArrowRightIcon size={15} /></button>} />
    <section className="growth-hero card"><div className="growth-hero-score"><ScoreRing value={scores.overall} size="large" label="Business Growth Score" caption={<span>Based on available signals</span>} /></div><div className="growth-explainer"><div className="eyebrow">YOUR SNAPSHOT</div><h2>{scores.overall !== null && scores.overall >= 60 ? 'A solid base, with room to grow.' : 'You have a clear next step.'}</h2><p>This is a directional score, not a scientific measurement. It only uses signals we can verify from your website and actions in this workspace.</p><div className="score-legend"><span><i className="legend-dot blue" /> Website</span><span><i className="legend-dot green" /> Activity</span><span><i className="legend-dot amber" /> AI readiness</span></div></div><div className="growth-spark">✦<span>Small improvements<br />compound over time.</span></div></section>
    <section className="score-grid"><div className="card score-breakdown"><div className="card-title-row"><div><div className="eyebrow">THE BREAKDOWN</div><h2>What makes up your score?</h2></div><InfoIcon size={18} /></div><div className="score-rows"><ScoreRow label="Website" value={scores.website} color="blue" detail="Clarity and useful information" /><ScoreRow label="Reviews" value={scores.reviews} color="green" detail="Your review activity here" /><ScoreRow label="Content" value={scores.content} color="green" detail="Your content activity here" /><ScoreRow label="AI visibility" value={scores.aiVisibility} color="amber" detail="Website AI readiness signals" /></div><p className="score-disclaimer"><InfoIcon size={14} /> Scores update when we have new information. Missing data is shown honestly.</p></div><div className="card action-card"><div className="eyebrow">NEXT BEST MOVES</div><h2>Start with these.</h2><div className="action-list">{actions.map((action, index) => <div key={action}><span>{String(index + 1).padStart(2, '0')}</span><p>{action}</p><CheckIcon size={16} /></div>)}</div><button className="text-button" onClick={() => onNavigate('today')}>Go to today’s actions <ArrowRightIcon size={15} /></button></div></section>
    <section className="ai-visibility-section"><button className="ai-section-heading" onClick={() => { setShowAI((value) => !value); onVisibilityView?.(); }}><div className="ai-heading-left"><div className="ai-icon"><SparkIcon size={21} /></div><div><div className="eyebrow">AI VISIBILITY</div><h2>Can assistants understand your business?</h2><p>Website signals that help AI systems describe you accurately.</p></div></div><div className="ai-heading-right"><span className="ai-score-pill">{scores.aiVisibility === null ? 'Not enough data' : `${scores.aiVisibility} / 100`}</span><ChevronDownIcon size={19} /></div></button>{showAI && <div className="ai-panel"><div className="ai-panel-copy"><h3>What this checks</h3><p>AI assistants increasingly help people discover local businesses. This section checks whether your website gives them enough clear, consistent context.</p><div className="check-list">{[
      ['Business name and location', profile.checks?.businessNameClarity && profile.checks?.locationClarity], ['Services and products', profile.checks?.serviceClarity], ['About and FAQ information', profile.checks?.aboutInformation && profile.checks?.faqPresence], ['Contact and important pages', profile.checks?.contactClarity && profile.checks?.importantPages], ['Structured data and technical access', profile.checks?.schemaPresence && profile.checks?.robotsTxt],
    ].map(([label, value]) => <div key={String(label)}><span className={`check-status ${value === true ? 'yes' : value === false ? 'no' : 'unknown'}`}>{value === true ? '✓' : value === false ? '!' : '—'}</span><span>{label}</span><small>{value === true ? 'Found' : value === false ? 'Needs attention' : 'Not checked'}</small></div>)}</div></div><div className="issue-box"><div className="issue-box-label">ISSUES FOUND</div>{issues.length ? issues.map((issue) => <div className="issue-item" key={issue}><span>!</span>{issue}</div>) : <p>No major issues detected from the available signals.</p>}<div className="ai-cta"><div><strong>Want help implementing this?</strong><span>Get a human review of your AI visibility.</span></div><button className="button button-dark" onClick={onGeoCta}>Improve my AI visibility <ExternalIcon size={15} /></button></div></div></div>}</section>
    <p className="powered-note">LocalBiz Copilot is a free operating tool. AI visibility implementation help is optional and provided by MultiHub GEO.</p>
  </div>;
}
