import { useEffect, useState } from 'react';
import type { BusinessProfile } from '../types';
import { PageHeader } from '../components/PageHeader';
import { GlobeIcon, LockIcon, LogOutIcon, RefreshIcon } from '../components/Icons';

export function ProfilePage({ profile, onSave, onReanalyze, onReset, onToast }: { profile: BusinessProfile; onSave: (profile: BusinessProfile) => void; onReanalyze: () => void; onReset: () => void; onToast: (message: string) => void }) {
  const [draft, setDraft] = useState(profile);
  useEffect(() => setDraft(profile), [profile]);
  const update = (key: keyof BusinessProfile, value: string) => setDraft((current) => ({ ...current, [key]: value }));
  return <div className="page"><PageHeader eyebrow="PROFILE" title="Your business, your way." description="Check what we found and fill in the blanks. Better context means more useful daily guidance." action={<button className="button button-light" onClick={onReanalyze}><RefreshIcon size={16} /> Re-analyze website</button>} /><section className="card profile-card"><div className="profile-card-title"><div className="large-avatar">{profile.businessName.slice(0, 1)}</div><div><h2>{profile.businessName}</h2><span>{profile.industry} {profile.location && `· ${profile.location}`}</span><a href={profile.websiteUrl} target="_blank" rel="noreferrer"><GlobeIcon size={14} /> {profile.websiteUrl.replace(/^https?:\/\//, '')}</a></div><span className={`mode-chip ${profile.analysisMode}`}>{profile.analysisMode === 'demo' ? 'Demo data' : profile.analysisMode === 'verified' ? 'Website analyzed' : 'Local preview'}</span></div><div className="profile-fields"><label>Business name<input value={draft.businessName} onChange={(event) => update('businessName', event.target.value)} /></label><label>Industry<input value={draft.industry} onChange={(event) => update('industry', event.target.value)} /></label><label>City or area<input value={draft.location} onChange={(event) => update('location', event.target.value)} placeholder="e.g. Amsterdam" /></label><label>What you do<textarea value={draft.description} onChange={(event) => update('description', event.target.value)} rows={3} placeholder="A short, clear description of your business" /></label><label>Main products or services<input value={draft.productsServices.join(', ')} onChange={(event) => setDraft((current) => ({ ...current, productsServices: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) }))} placeholder="Separate with commas" /></label><label>Audience<input value={draft.audience} onChange={(event) => update('audience', event.target.value)} /></label></div><button className="button button-dark" onClick={() => { onSave({ ...draft, analysisMode: draft.analysisMode === 'demo' ? 'manual' : draft.analysisMode }); onToast('Business details saved.'); }}>Save business details</button></section><section className="privacy-card"><LockIcon size={18} /><div><strong>Your data stays yours.</strong><p>We start without an account. Your current workspace is saved in this browser. We only send information when you ask for analysis, AI generation or an opted-in report.</p></div></section><section className="danger-zone"><div><div className="eyebrow">START OVER</div><h3>Analyze a different business</h3><p>Clear this local workspace and return to the start screen.</p></div><button className="button button-light" onClick={onReset}><LogOutIcon size={16} /> Clear workspace</button></section></div>;
}
