import { useState } from 'react';
import type { BusinessProfile, Tone } from '../types';
import { PageHeader } from '../components/PageHeader';
import { CopyIcon, QrIcon, RefreshIcon, SparkIcon } from '../components/Icons';
import { aiProvider } from '../lib/ai';
import QRCode from 'qrcode';

export function ReviewsPage({ profile, onToast, onReviewUsed, onEvent }: { profile: BusinessProfile; onToast: (message: string) => void; onReviewUsed: () => void; onEvent?: (name: string) => void }) {
  const [review, setReview] = useState('');
  const [tone, setTone] = useState<Tone>('friendly');
  const [reply, setReply] = useState('');
  const [busy, setBusy] = useState(false);
  const [reviewUrl, setReviewUrl] = useState('');
  const [qr, setQr] = useState('');
  const generateReply = async () => { if (!review.trim()) return; setBusy(true); try { setReply(await aiProvider.generateReviewReply(review, tone, profile)); onReviewUsed(); } catch (error) { onToast(error instanceof Error ? error.message : 'Could not generate a reply.'); } finally { setBusy(false); } };
  const createQr = async () => { try { if (!/^https?:\/\//i.test(reviewUrl.trim())) throw new Error('Please paste a complete review link starting with https://'); setQr(await QRCode.toDataURL(reviewUrl.trim(), { width: 420, margin: 2, color: { dark: '#163b36', light: '#ffffff' } })); onEvent?.('review_qr_created'); onToast('Your review QR is ready.'); } catch (error) { onToast(error instanceof Error ? error.message : 'Could not create the QR code.'); } };
  const copy = async () => { await navigator.clipboard?.writeText(reply); onToast('Reply copied to clipboard.'); };
  const downloadQr = () => { if (!qr) return; const link = document.createElement('a'); link.href = qr; link.download = `${profile.businessName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-review-qr.png`; link.click(); };
  return <div className="page"><PageHeader eyebrow="REVIEWS" title="Make every review count." description="Reply like a real person, then make it easy for happy customers to share their experience." />
    <div className="review-layout"><section className="card review-card"><div className="card-title-row"><div><div className="eyebrow">REPLY ASSISTANT</div><h2>What did your customer say?</h2></div><div className="soft-icon peach"><SparkIcon size={20} /></div></div><textarea value={review} onChange={(event) => setReview(event.target.value)} placeholder="Paste a review here…\n\nExample: Coffee was great but I waited 20 minutes." rows={6} /><div className="tone-row"><span>Reply style</span>{(['friendly', 'professional', 'short'] as Tone[]).map((value) => <button key={value} className={tone === value ? 'selected' : ''} onClick={() => setTone(value)}>{value.charAt(0).toUpperCase() + value.slice(1)}</button>)}</div><button className="button button-dark full-button" onClick={generateReply} disabled={busy || !review.trim()}>{busy ? 'Writing a thoughtful reply…' : reply ? 'Regenerate reply' : 'Generate reply'}<RefreshIcon size={16} /></button></section>
      <section className="card result-card">{reply ? <><div className="result-label"><span className="result-dot" /> SUGGESTED REPLY</div><p className="reply-text">{reply}</p><div className="result-actions"><button className="button button-dark" onClick={copy}><CopyIcon size={16} /> Copy reply</button><button className="text-button" onClick={generateReply}><RefreshIcon size={15} /> Try another</button></div><div className="responsible-note">Written to acknowledge the customer—not to argue or ask for a better rating.</div></> : <div className="empty-result"><div className="empty-result-icon">✦</div><h3>Your reply will appear here</h3><p>We’ll keep it short, human and appropriate for your business.</p></div>}</section></div>
    <section className="card qr-section"><div className="qr-copy"><div className="eyebrow">REVIEW QR CARD</div><h2>Turn a good visit into an easy next step.</h2><p>Paste your public review link and create a simple QR code you can place by the till, on a table or in a thank-you note.</p><div className="qr-input-row"><input value={reviewUrl} onChange={(event) => setReviewUrl(event.target.value)} placeholder="https://g.page/your-business/review" type="url" /><button className="button button-dark" onClick={createQr}><QrIcon size={16} /> Create QR</button></div><p className="form-note"><span className="green-check">✓</span> No review gating. No incentives. Just an honest invitation.</p></div><div className="qr-preview"><div className="print-card"><div className="print-brand">{profile.businessName}</div>{qr ? <img src={qr} alt="Review QR code" /> : <div className="qr-placeholder"><QrIcon size={84} /></div>}<strong>Enjoyed your visit?</strong><span>Leave us a review ♥</span></div>{qr && <button className="text-button" onClick={downloadQr}>Download PNG <QrIcon size={14} /></button>}</div></section>
  </div>;
}
